# -*- coding: utf-8 -*-
"""Differential Equation System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYOAbcFGg3ZwSPKERBcvhbNZxpVSOByF
"""

import numpy as np
import matplotlib.pyplot as plt

#defining differential equation system
def dynamics(x, t):
    dx=[0,0,0,0]
    dx[0]= 1-4*x[0]-2*x[0]*x[1]
    dx[1]= 4*x[0]-2*x[0]*x[1]
    dx[2]= 2*x[0]*x[1] - 3*x[2]
    dx[3]= 2*x[0]*x[1] - 4*x[3]
    return dx

#time grid and initial values
t_start=0; t_end=10; dt=0.1
times=np.arange(t_start, t_end+dt, dt)
xinitial=[6,5,1,5]


from scipy.integrate import odeint
x=odeint(dynamics, xinitial, times)

#generate figure
plt.figure()
plt.plot(times, x[:,0], label="[A]", linewidth=1)
plt.plot(times, x[:,1], label="[B]", linewidth=1)
plt.plot(times, x[:,2], label="[C]", linewidth=1)
plt.plot(times, x[:,3], label="[D]", linewidth=1)
plt.xlabel("Time")
plt.ylabel("concentration")
plt.legend()